version: '3'

services:
  ticket-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-3002}:${PORT:-3002}'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3002}
      - DATABASE_HOST=${DATABASE_HOST:-ticket-postgres}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres123}
      - DATABASE_NAME=${DATABASE_NAME:-ticket_service}
      - MONOLITH_SERVICE_URL=${MONOLITH_SERVICE_URL:-http://host.docker.internal:3001}
    restart: unless-stopped
    depends_on:
      ticket-postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ticket-postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres123}
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-ticket_service}
    ports:
      - '${DATABASE_PORT:-5433}:5432'
    volumes:
      - ticket_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER:-postgres}']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  ticket_postgres_data: