import { Injectable, NotFoundException, Inject } from '@nestjs/common';
import { Product } from '../../domain/entities/product.entity';
import {
  ProductRepository,
  PRODUCT_REPOSITORY_TOKEN, // Corrected token usage
} from '../../domain/repositories/product.repository';
import {
  CreateProductDto,
  UpdateProductDto,
  ProductResponseDto,
} from '../dtos/product.dto'; // Added ProductResponseDto

@Injectable()
export class ProductService {
  constructor(
    @Inject(PRODUCT_REPOSITORY_TOKEN) // Corrected token
    private productRepository: ProductRepository,
  ) {}

  private mapToResponseDto(product: Product): ProductResponseDto {
    return {
      id: product.id,
      name: product.name,
      description: product.description,
      price: product.price,
      stock: product.stock,
      createdAt: product.createdAt,
      updatedAt: product.updatedAt,
    };
  }

  private mapArrayToResponseDto(products: Product[]): ProductResponseDto[] {
    return products.map((p) => this.mapToResponseDto(p));
  }

  async findAll(): Promise<ProductResponseDto[]> {
    const products = await this.productRepository.findAll();
    return this.mapArrayToResponseDto(products);
  }

  async findById(id: string): Promise<ProductResponseDto> {
    const product = await this.productRepository.findById(id);
    if (!product) {
      throw new NotFoundException(`Product with ID ${id} not found`);
    }
    return this.mapToResponseDto(product);
  }

  async create(
    createProductDto: CreateProductDto,
  ): Promise<ProductResponseDto> {
    // Product ID is auto-generated by TypeORM
    // const productEntity = new Product(createProductDto); // DTO is passed to repo
    const newProduct = await this.productRepository.create(createProductDto);
    return this.mapToResponseDto(newProduct);
  }

  async update(
    id: string,
    updateProductDto: UpdateProductDto,
  ): Promise<ProductResponseDto> {
    // Repository's update method should handle checking existence or TypeORM will throw error
    const updatedProduct = await this.productRepository.update(
      id,
      updateProductDto,
    );
    if (!updatedProduct) {
      // This might occur if findById in repo returns null after update
      throw new NotFoundException(
        `Product with ID ${id} not found or failed to update.`,
      );
    }
    return this.mapToResponseDto(updatedProduct);
  }

  async delete(id: string): Promise<{ success: boolean; productId: string }> {
    // Simplified response
    const productToDelete = await this.productRepository.findById(id);
    if (!productToDelete) {
      throw new NotFoundException(
        `Product with ID ${id} not found for deletion.`,
      );
    }
    const success = await this.productRepository.delete(id);
    if (!success) {
      // This case might be redundant if findById already threw
      throw new NotFoundException(
        `Product with ID ${id} could not be deleted.`,
      );
    }
    return {
      success: true,
      productId: id,
    };
  }
}
